AWSTemplateFormatVersion: "2010-09-09"
Description: "Criando o S3, SNS e o SQS da aplicacao Spring Boot"
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: s3-local-lab-localstack
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "sns-local-lab-localstack"
      DisplayName: "sns-local-lab-localstack"
  SQSQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "sqs-local-lab-localstack"
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "DLQ"
            - "Arn"
        maxReceiveCount: 3
  DLQ:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "sqs-dlq-local-lab-localstack"
  SNSSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Protocol: "sqs"
      TopicArn: !Ref SNSTopic
      Endpoint: !GetAtt SQSQueue.Arn
  SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: SNSTopic
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource:
              Fn::GetAtt:
                - SQSQueue
                - Arn
        Version: "2012-10-17"
      Queues:
        - Ref: SQSQueue

Outputs:
  S3BucketOutput:
    Value: !Ref S3Bucket
  SNSTopicOutput:
    Value: !Ref SNSTopic
  SQSQueueOutput:
    Value: !Ref SQSQueue
  DLQOutput:
    Value: !Ref DLQ